name: bwaflutix
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  build_runner: ^2.1.7
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.4
  dotted_line: ^3.1.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^9.3.1
  flutter_screenutil: ^5.2.0
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  http: ^0.13.4
  image_cropper: ^1.4.1
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4+8
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6595
  path_provider: ^2.0.9
  permission_handler: ^8.3.0
  qr_flutter: ^4.0.0
  random_string: ^2.3.1
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
